### ISSUE TITLE
デプロイする条件を変更する

### ISSUE THREAD

**Issue by fuji8** [traPtitech/knoQ#113]
### 既存条件
- *latest*
https://github.com/traPtitech/knoQ/blob/81dcfa32788e3290f4821204807f054e79a8d26f/.github/workflows/main.yml#L1-L4
- *beta*
https://github.com/traPtitech/knoQ/blob/81dcfa32788e3290f4821204807f054e79a8d26f/.github/workflows/develop.yml#L1-L4

### 変更案
それぞれ `master`, `develop`ブランチという条件を追加する

**Comment by fuji8** [comment]
実現性は要検証

**Comment by ras0q** [comment]
mainにpushされたらステージング環境のdocker imageを、vx.y.zタグがpushされたら本番環境のimageを作るようにした
