### ISSUE TITLE
テストの失敗

### ISSUE THREAD

**Issue by fuji8** [traPtitech/knoQ#213]
> ?   	github.com/traPtitech/knoQ/infra/google	[no test files]
panic: Post "http://localhost:3000/api/v3/login": http: ContentLength=33 with Body length 0
goroutine 1 [running]:
github.com/traPtitech/knoQ/infra/traq.TestMain(0xc00046e380)
	/home/runner/work/knoQ/knoQ/infra/traq/traq_test.go:52 +0xd33
main.main()
	_testmain.go:43 +0x165
FAIL	github.com/traPtitech/knoQ/infra/traq	5.021s
FAIL

https://github.com/traPtitech/knoQ/issues/17 の実装が良くなさそう

**Comment by fuji8** [comment]
f36bb0b

**Comment by ras0q** [comment]
infra/traq/traq_test.goを消したので一旦close
