### ISSUE TITLE
参加予定システム（schedule）

### ISSUE THREAD

**Issue by fuji8** [traPtitech/knoQ#216]
#173 
#12 の一部

### 概略
イベント開催前に、ユーザが出席・欠席の予定を表明する。
[参加予定](https://github.com/traPtitech/knoQ/wiki/event#%E5%8F%82%E5%8A%A0%E4%BA%88%E5%AE%9Av21%E5%AE%9F%E8%A3%85%E4%BA%88%E5%AE%9A)

### TODO
- [x] 自分の参加予定を編集
- [x] イベント作成時、その時点でのグループメンバーを**pending**で参加予定に追加
- [x] イベントのレスポンスに参加予定を付けて返す
- [x] 作成・更新時のtraQへのwebhookの文章の変更
- [x] query parserのuserを"userが欠席予定ではないイベントを返す"に変更 
- [x] #218

**Comment by ras0q** [comment]
おそらく完了したのでclose
