### ISSUE TITLE
配信するiCalに"ATTENDEE"."PARTSTAT"を追加

### ISSUE THREAD

**Issue by fuji8** [traPtitech/knoQ#218]

**Comment by fuji8** [comment]
iCalは[rfc5545](https://datatracker.ietf.org/doc/html/rfc5545) で策定されている規格であり，googleカレンダーなどは基本的にこれに対応している．
そのうちの参加予定に近い概念が，"ATTENDEE"."PARTSTAT" になる．
これを追加してもgoogleカレンダー上では何も変化ないが，appleのカレンダーでは参加予定が見れる

**Comment by fuji8** [comment]
例
```ics
BEGIN:VEVENT
DTSTART;VALUE=DATE:20220330
DTEND;VALUE=DATE:20220331
DTSTAMP:20220330T073223Z
ORGANIZER:mailto:hoge@group.calendar.google.com
UID:hogeUID@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=haya10
 .88ha@gmail.com;X-NUM-GUESTS=0:mailto:haya10.88ha@gmail.com
CREATED:20220330T072522Z
DESCRIPTION:
LAST-MODIFIED:20220330T072958Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:ああああ
TRANSP:TRANSPARENT
END:VEVENT
```

<img width="344" alt="スクリーンショット 2022-03-30 16 37 25" src="https://user-images.githubusercontent.com/40717344/160777435-ca38e5a2-0ba4-43a8-8e04-66ef17a48289.png">

**Comment by iChemy** [comment]
iCal生成に使用している[lestrrat-go](https://pkg.go.dev/github.com/lestrrat-go/ical@v0.0.0-20201229070544-61f83f92eaf4)
では
ATTENDEEプロパティを加えるという操作はは(VEVENTじゃなくて)VTODOコンポーネントにのみ実装されている
[VEVENTにプロパティを加えるメソッド](https://github.com/lestrrat-go/ical/blob/61f83f92eaf4/event_gen.go#L51)
[VTODOにプロパティを加えるメソッド](https://github.com/lestrrat-go/ical/blob/61f83f92eaf456614639f3c681f7fa8569ec0e37/todo_gen.go#L51)

AppleカレンダーだとVTODO要素が反映されない(気がする)．以下の例で試したところ読み込まれなかった．
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:github.com/lestrrat-go/ical
BEGIN:VTIMEZONE
TZID:Asia/Tokyo
BEGIN:STANDARD
DTSTART:19700101T000000
TZNAME:JST
TZOFFSETFROM:+9000
TZOFFSETTO:+9000
END:STANDARD
END:VTIMEZONE
BEGIN:VTODO
UID:ichemy@example.com
DTSTAMP:20230630T073223Z
DUE;VALUE=DATE:20230701
SUMMARY:Sample TODO in 2023
CLASS:CONFIDENTIAL
CATEGORIES:FAMILY,FINANCE
STATUS:NEEDS-ACTION
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=ichemy;
 X-NUM-GUESTS=0:mailto:ichemy@gmail.com
END:VTODO
END:VCALENDAR
```
あるいは私が要件を満たせておらずただ単に読み込めてない可能性も?

**Comment by ras0q** [comment]
使ってるライブラリのスター数そんな多くなくて今後追加される予定も少なそうですね

軽く調べただけだけど https://github.com/arran4/golang-ical とかの方がスター数多そうでATTENDEEの追加もありそうでした
https://github.com/arran4/golang-ical/blob/f69e132f2b0c9c73cff9ce88c3d6cc1af4bc3e2d/components.go#L292

もしくはどっちも使わずに自分で実装するのもアリだと思います

**Comment by ras0q** [comment]
https://github.com/traPtitech/knoQ/pull/445
