### ISSUE TITLE
イベント終了後にイベントを編集したときに#services/knoQに通知を投稿しないようにしたい

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/knoQ#399]
https://q.trap.jp/messages/cdd9f6eb-df08-4f03-a7d7-19ca1ee46756

**Comment by Nzt3-gh** [comment]
https://github.com/traPtitech/knoQ/blob/main/presentation/event.go#L165
ここの行が「開始時刻が現在時刻より後」の判定で、開始後のイベントの編集でメンションは飛ばないようです。

**Comment by ras0q** [comment]
コメント遅れてすみません🙇‍♂️🙇‍♂️🙇‍♂️

一応これはtimestartを見てるのでそこだけ若干違いますが大体あってそうです👍
そこの仕様も終了前は通知、終了後は通知しないように変えていいと思います

ネストがかなり深くなってるので終了してたら早期リターンすると良さそうですね
