### ISSUE TITLE
traQへのリクエストにgo-traqを使う

### ISSUE THREAD

**Issue by ras0q** [traPtitech/knoQ#439]
↓みたいなのを全部go-traqに変える
https://github.com/traPtitech/knoQ/blob/cb9fc326df54acd5702df6cee2deb8fe32f146a4/infra/traq/user.go#L15-L29

**Comment by ras0q** [comment]
OAuth2トークンを使ったAPIClientの作成は↓でできる
```go
	traqconf := traq.NewConfiguration()
	traqconf.HTTPClient = conf.Client(c.Request().Context(), tok)
	client := traq.NewAPIClient(traqconf)
```
https://github.com/ras0q/traq-oauth2/blob/b35ef45bb5d52aab749b863582b4b0a3c4e2dfd7/example/webapp-with-library/main.go#L126-L128

**Comment by Nzt3-gh** [comment]
現在traQにリクエストをしている箇所は
traQにメッセージを送信
https://github.com/traPtitech/knoQ/blob/main/utils/api.go#L20-L48
ユーザー情報の取得
https://github.com/traPtitech/knoQ/blob/main/infra/traq/user.go#L15-L29
複数のユーザー情報の取得
https://github.com/traPtitech/knoQ/blob/main/infra/traq/user.go#L31-L51
自分のユーザー情報の取得
https://github.com/traPtitech/knoQ/blob/main/infra/traq/user.go#L53-L67
グループ情報の取得
https://github.com/traPtitech/knoQ/blob/main/infra/traq/group.go#L14-L28
複数のグループ情報の取得
https://github.com/traPtitech/knoQ/blob/main/infra/traq/group.go#L30-L44
ユーザー情報の取得
https://github.com/traPtitech/knoQ/blob/main/infra/traq/group.go#L46-L70

**Comment by ras0q** [comment]
もう少しわかりやすい名前にすれば良かったと思ってるけどwebhookは https://github.com/ras0q/traq-writer とかがあるので記述減らしたい&デバッグ環境でtraQに通知飛ばしたくないときは参考にしてください
