### ISSUE TITLE
本番環境のビルド時間を削減する

### ISSUE THREAD

**Issue by ras0q** [traPtitech/knoQ#475]
traQで3分くらいなのにknoQでは8分ほどかかっている

**Comment by ras0q** [comment]
`RUN --mount=type=cache`使ったら早くなるかも

**Comment by motoki317** [comment]
> traQで3分くらいなのにknoQでは8分ほどかかっている

Goのcross-compileを使っていなくて、QEMUを使ってamd64のマシン上でarm64のgoでビルドしてるから
たぶん

https://github.com/traPtitech/traQ/blob/b88d1c38fa0fc5035debe0ae50163ebf9417f90b/Dockerfile#L1
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
